#include "formats.h"

enum {

        TXT_MODULE_NAME,

        TXT_IDEA_OWN_MSG,
        TXT_IDEA_OWN_MSG_CHANNEL,
        TXT_IDEA_OWN_MSG_PRIVATE,
	TXT_IDEA_OWN_MSG_PRIVATE_QUERY,

        TXT_IDEA_PUBMSG_ME,
        TXT_IDEA_PUBMSG_ME_CHANNEL,
	TXT_IDEA_PUBMSG_HILIGHT,
	TXT_IDEA_PUBMSG_HILIGHT_CHANNEL,
        TXT_IDEA_PUBMSG,
        TXT_IDEA_PUBMSG_CHANNEL,
        TXT_IDEA_MSG_PRIVATE,
        TXT_IDEA_MSG_PRIVATE_QUERY,

};

extern FORMAT_REC idea_formats[];
